services:
  hardened-base:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    restart: on-failure:3
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=32m
      - /run:rw,noexec,nosuid,size=16m

  hardened-tiny:
    extends:
      service: hardened-base
    mem_limit: 128m
    memswap_limit: 128m
    pids_limit: 64

  hardened-small:
    extends:
      service: hardened-base
    mem_limit: 256m
    memswap_limit: 256m
    pids_limit: 128

  hardened-medium:
    extends:
      service: hardened-base
    mem_limit: 512m
    memswap_limit: 512m
    pids_limit: 192

  hardened-large:
    extends:
      service: hardened-base
    mem_limit: 1g
    memswap_limit: 1g
    pids_limit: 256

  hardened-xlarge:
    extends:
      service: hardened-base
    mem_limit: 2g
    memswap_limit: 2g
    pids_limit: 512

  hardened-xxlarge:
    extends:
      service: hardened-base
    mem_limit: 3g
    memswap_limit: 3g
    pids_limit: 768

  hardened-no-limits:
    extends:
      service: hardened-base

  limits-small:
    mem_limit: 256m
    memswap_limit: 256m
    pids_limit: 128

  limits-medium:
    mem_limit: 512m
    memswap_limit: 512m
    pids_limit: 192

  limits-large:
    mem_limit: 1g
    memswap_limit: 1g
    pids_limit: 256

  limits-xlarge:
    mem_limit: 2g
    memswap_limit: 2g
    pids_limit: 512

  limits-xxlarge:
    mem_limit: 3g
    memswap_limit: 3g
    pids_limit: 768

  postgres:
    extends:
      service: hardened-medium
    tmpfs:
      - /var/run/postgresql:rw,noexec,nosuid,mode=2775,uid=999,gid=999,size=16m
    user: 999:999
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  redis:
    extends:
      service: hardened-small
    image: redis:8
    user: 999:999
    environment:
      - TZ=Europe/Zurich
